replicaCount: 1  # You can change this to 3 for high availability if required

image:
  repository: wordpress
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: wordpress.oracles.gift
      paths:
        - path: /
          pathType: ImplementationSpecific
tls:
  - secretName: wordpress-tls
    hosts:
      - wordpress.oracles.gift

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# PostgreSQL Database Configuration
postgresql:
  enabled: true  # Set to true to enable PostgreSQL
  postgresqlUsername: wordpress  # Username for the WordPress database
  postgresqlPassword: db$123  # Password for the WordPress database user
  postgresqlDatabase: wordpress  # Name of the WordPress database
  persistence:
    enabled: true
    size: 10Gi  # Adjust the size as needed

# External database config for WordPress (disabled since using PostgreSQL)
externalDatabase:
  enabled: false