replicaCount: 1

image:
  repository: wordpress
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: wordpress.oracles.gift
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: wordpress-application-wordpress  # Ensure this matches your service name
              port:
                number: 80
  tls:
    - secretName: wordpress-tls
      hosts:
        - wordpress.oracles.gift

resources: {}

# Autoscaling block added
autoscaling:
  enabled: false  # Set to false if not using autoscaling
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# PostgreSQL Configuration
postgresql:
  enabled: true
  postgresqlUsername: wordpress
  postgresqlPassword: db$123
  postgresqlDatabase: wordpress
  persistence:
    enabled: true
    size: 10Gi

# External database (if needed)
externalDatabase:
  enabled: false
  host: ""
  user: ""
  password: ""
  database: ""
  secretName: ""