replicaCount: 3 # You can change this to 3 for high availability if required

image:
  repository: wordpress
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: wordpress.oracles.gift
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: wordpress-tls
     hosts:
       - wordpress.oracles.gift

mariadb:
  enabled: true  # Enable MariaDB deployment within the same Helm chart
  architecture: standalone  # You can set it to replication for high availability
  auth:
    rootPassword: root$123  # Root password for MariaDB
    username: wordpress      # WordPress user
    password: db$123         # Password for the WordPress user
    database: wordpress      # Name of the database
  primary:
    persistence:
      enabled: false  # Disable persistence for testing, but enable it in production

externalDatabase:
  enabled: false  # Set to false since we are using the internal MariaDB

resources: {}