apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    app: {{ include "application.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "application.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "application.name" . }}
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ include "application.fullname" . }}-postgresql
        - name: WORDPRESS_DB_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "application.fullname" . }}-postgresql-secret
              key: postgresql-password
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.postgresql.postgresqlDatabase }}