apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}-wordpress
  labels:
    app: {{ include "application.name" . }}
spec:
  selector:
    app: {{ include "application.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80