apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}-postgresql
  labels:
    app: {{ include "application.name" . }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ include "application.name" . }}-postgresql