# Default values for the WordPress Helm chart

replicaCount: 1

image:
  repository: wordpress
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "php8.3-apache"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: wordpress.oracles.gift
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: wordpress-tls
     hosts:
       - wordpress.oracles.gift

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Database Configuration
mariadb:
  enabled: true
  auth:
    rootPassword: example_root_password # Default placeholder for root password
    database: wordpress # Default database name
    username: wordpress # Default database username
    password: example_password # Default placeholder for user password
  primary:
    persistence:
      enabled: true
      size: 8Gi # Default persistence size

# External Database (set to false because we are using MariaDB)
externalDatabase:
  host: mariadb
  user: wordpress
  password: example_password # Default placeholder for user password
  database: wordpress
  port: 3306

# Ensure WordPress connects to the correct database
wordpress:
  debug: true
  mariadb:
    enabled: true